### ISSUE TITLE
Add moves and color-code them

### ISSUE THREAD

**Issue by Wegi** [Phaetec/pogo-cruncher#15]

**Comment by Wegi** [comment]
Have to get a lookup table to translate numbers to text/type.

**Comment by n2o** [comment]
Attacks added in c8e516f9e7d5533eaef604551b0dad7cf7180310

**Comment by n2o** [comment]
Color-Coding still missing... Have to think about it first

**Comment by leevigraham** [comment]
I don't think you should worry about colour coding. There's a8 move groups which would make it really hard to recognise subtle colours.

I quickly mocked up this which simply solves the problem:

<img width="1091" alt="screen shot 2016-08-16 at 8 09 17 pm" src="https://cloud.githubusercontent.com/assets/25124/17695801/93c624f2-63ed-11e6-8505-a8bb2fa044e3.png">

Changes:

Add move type in small underneath the move name. The main purpose of showing the move type for me is to determine if there's a STAB bonus

Reduce the width of the other columns:

- Combine Name + Nickname in the same format as move + move group
- Change IV Perfect % to IV%
- Change Attack, Defence and Stamina to AT, DF and ST

**Comment by n2o** [comment]
Good idea, thanks for your suggestions. I will add this in the evening.
