### ISSUE TITLE
Feature Request: Log/progress meter while deleting

### ISSUE THREAD

**Issue by Gillingham** [Phaetec/pogo-cruncher#19]
While some progress bar via ajax on the webUI would be nice, just doing simple debug prints on the console would make large deletions much clearer rather than sitting at a blank screen for many minutes.

**Comment by Wegi** [comment]
Thanks for your Input, adding this to the TODO list.

**Comment by Wegi** [comment]
Added a new API endpoint which returns deletion status in commit 54f0e8a .

You can query the status until the original request for deletion returns `{'status': 'ok'}`.

Please add a progress bar based upon this.

**Comment by n2o** [comment]
Implemented in 9bc9215
