### ISSUE TITLE
Frontend trying to connect to localhost:5000/api/login instead of [docker-machine ip default]:5000/api/login

### ISSUE THREAD

**Issue by masiarb** [Phaetec/pogo-cruncher#20]
Hello,

Built and run. Input my data, click on login, nothing happens. No loading page, no backend logs. Frontend gives the following error in the JS console `cruncher.js:809 OPTIONS http://localhost:5000/api/login net::ERR_CONNECTION_REFUSED`. Seems to me it has to use `docker-machine ip default` instead of fixed localhost to correctly contact login api, right?

**Comment by OSwoboda** [comment]
You're right, I have the same problem. I'm using it on windows with the docker VM and that's why the IP isn't localhost.

**Comment by masiarb** [comment]
Yup. I hardcoded my IP in `config.cljs` and now it works. Maybe make it automatic?

**Comment by Wegi** [comment]
Thanks for the report. Will investigate as soon as im off work.

**Comment by Delco64** [comment]
How do I hardcode/access the config.cljs file?

**Comment by OSwoboda** [comment]
I've found a simplier solution on windows with docker toolbox installed:
1. Open Oracle VirtualBox
2. Go to Settings of your Docker VM
3. Choose Advanced at Network Settings
4. Choose Port-Forwarding
5. Add a new Rule:
Host-IP: 127.0.0.1
Host-Port: 8888
Guest-Port: 8888
Leave Guest-IP blank.
6. Now you can access pogo-cruncher in your host browser with http://localhost:8888

**Comment by 80rrego** [comment]
<thanks PSwoboda you solve my life! hahaha easy and fast

**Comment by 80rrego** [comment]
Now the app is not loggin didnt say anything

**Comment by OSwoboda** [comment]
Sry, you need to add a rule for port 5000, too.

**Comment by Wegi** [comment]
Can someone with the windows problems try this version and report results? My Windows machine is unavailable right now unfortunately.

https://github.com/Wegi/pogo-cruncher/releases/tag/0.1.3 (Current master HEAD)

I changed the ip inside the config to listen on 0.0.0.0 which should be available outside of the container as well. Also the containers are now extra linked.

**Comment by OSwoboda** [comment]
I've tested it and removed my port forwarding rules.
`cruncher.js:809 OPTIONS http://0.0.0.0:5000/api/login net::ERR_ADDRESS_INVALID`

**Comment by Wegi** [comment]
Hm, maybe I try to include a .bat file for automatic configuration for windows users. Gotta test that first.

**Comment by Wegi** [comment]
Next try, is someone willing to test the newest commit?
Either pull newest version from source or change config.cljs to
```
(ns cruncher.config)

(def api {:host "http://backend:5000/"
          :init "api/init/"
          :base "api/"
          :login "api/login"
          :get-all-pokemon "api/pokemon"
          :crunch-selected-pokemon "api/pokemon/delete"})
```
If it still doesnt work, please respond with the terminal output. Would be much appreciated.

**Comment by Wegi** [comment]
I've added an alternative installation path for windows without docker. Please report results.

## Installation Setup for Windows user
You can also use the Linux / MAC OS docker setup, but for unknown reasons it does not work properly for most windows users. So use instructions below.

  1. Install [Python 3](https://www.python.org/downloads/).
    * Check "Add Python3.5 to PATH" during installation.
  2. Download the newest Windows release [here](https://github.com/Wegi/pogo-cruncher/releases).
  3. Unzip the folder.
  4. Open `cmd` or `Powershell`.
  5. Type `cd <C:/Path/to/the/folder>`
  6. Type `pip install -r requirements.txt`
  7. After this finishes you may start the cruncher as follows:

### Windows Startup 
  8. In the application folder type `python app.py`
  9. Now open the index.html in the folder with your preffered browser.

**Comment by masiarb** [comment]
For @Delco64 , `config.cljs` is in the `/frontend/src/cruncher/` folder. I am running on MacOSX so I can't test the setup!

**Comment by Wegi** [comment]
docker version doesnt seem to respond after pressing the login button. Any ideas @n2o ?

**Comment by Wegi** [comment]
Nevermind, seems to be an error on my end.

**Comment by n2o** [comment]
Docker for Windows released and we prepared a precompiled Docker image for it. See the installation section in the Wiki for more information. This should fix your installation problems.
