### ISSUE TITLE
New Issue Can't Login

### ISSUE THREAD

**Issue by 80rrego** [Phaetec/pogo-cruncher#23]
Lets see if somebody can help me, I already could open the app in browser.

But when I click login. It shows like if is working but nothing happen.

Did I forget to do something?

EDIT: AGAIN SORRY IT LOOKS LIKE SERVERS ARE DOWN

**Comment by Wegi** [comment]
Servers are working now again. Could you test it again?

If it is not working, can you tell me if you are using google or ptc login. And what the output in the terminal is. Thank you.

**Comment by 80rrego** [comment]
I can't login with PTC, I didn't try with google, the console just show the opening of the website

> ←[33mfrontend_1  |←[0m 10.0.2.2 - - [28/Jul/2016 17:28:02] "GET /bower_component
> s/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 -
> ←[33mfrontend_1  |←[0m 10.0.2.2 - - [28/Jul/2016 17:28:03] "GET /bower_component
> s/bootswatch-dist/css/bootstrap.min.css HTTP/1.1" 200 -
> ←[33mfrontend_1  |←[0m 10.0.2.2 - - [28/Jul/2016 17:28:03] "GET /bower_component
> s/fontawesome/css/font-awesome.min.css HTTP/1.1" 200 -
> ←[33mfrontend_1  |←[0m 10.0.2.2 - - [28/Jul/2016 17:28:03] "GET /css/style.css H
> TTP/1.1" 200 -
> ←[33mfrontend_1  |←[0m 10.0.2.2 - - [28/Jul/2016 17:28:03] "GET /bower_component
> s/jquery/dist/jquery.min.js HTTP/1.1" 200 -
> ←[33mfrontend_1  |←[0m 10.0.2.2 - - [28/Jul/2016 17:28:03] "GET /bower_component
> s/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 200 -
> ←[33mfrontend_1  |←[0m 10.0.2.2 - - [28/Jul/2016 17:28:03] "GET /js/compiled/cru
> ncher.js HTTP/1.1" 200 -
> ←[33mfrontend_1  |←[0m 10.0.2.2 - - [28/Jul/2016 17:28:03] "GET /bower_component
> s/fontawesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1" 200 -

![image](https://cloud.githubusercontent.com/assets/6773930/17222795/996864ca-54bf-11e6-84f9-c4784fc8f1e5.png)

I try with coordinates and with the name of the place

**Comment by 80rrego** [comment]
I dont install python 3.5 and im seeing from build the step 1

Step 1 : FROM python:3.5
 ---> 9152ad50a7f9

**Comment by Wegi** [comment]
Do you have something like `"POST /api/login HTTP/1.1" 200 -` in your terminal, when trying to log in?

Also can you try the newest version? There seems to be some issue with windows. You are using Windows10 I assume?

**Comment by 80rrego** [comment]
Windows 7 :p

**Comment by Wegi** [comment]
Can you try the newest release and see if it works now?

**Comment by 80rrego** [comment]
Yeah I just run the build I let you know in a minutes

**Comment by zheekl1599** [comment]
i have the same problem, i cant log in with google :(

**Comment by qzqzqz** [comment]
care guys
this seems to be a hack!

**Comment by qzqzqz** [comment]
hey dude,
dont know if u can see deleted comments, but i apparently made a really bad typo.
now it finally works and this script is great! :)

**Comment by Wegi** [comment]
Nice to hear. :) WIll leave this open for a week in case the issue still exists with someone.

**Comment by zheekl1599** [comment]
yess it works now, since the latest update :+1: thank you and keep up the good work!

**Comment by 80rrego** [comment]
I never write again, with the last update all work perfect Finally I could crunch all that pokemons! hahah thanks! For me this can be closed

**Comment by Wegi** [comment]
Good to hear. :)
