### ISSUE TITLE
Bug: Clicking Headers doesn't reverse sort

### ISSUE THREAD

**Issue by weblue** [Phaetec/pogo-cruncher#24]
Although using the headers to sort the Pokemon functions correctly, clicking on a header which is already being used to sort should reverse the sort order.

**Comment by Wegi** [comment]
Will add as a future feature.

**Comment by NaabKing** [comment]
this! :D It's really annoying i can only sort pokemons by "Z-A" and not "A-Z".

**Comment by n2o** [comment]
@NaabKing to make you happy: recently added this feature, will come up in the next release (or already in the dev-version)
