### ISSUE TITLE
Add more information for the pokemon

### ISSUE THREAD

**Issue by Tsunamii** [Phaetec/pogo-cruncher#26]
first of all this is a really nice tool :)

but to decide which pokemon is better there are some more stats that you could show:
- current atk, def, sta ((iv_value + base_value) * cp_multiplier)
- dps normal atk (power / time) * 1000
- dps special atk
- dps combined 
- potentional max dmg (atk* dps max)
- potentional dmg per cp (the higher the better for exp farming at gyms)

for mor information see my java tool: https://github.com/Tsunamii/IVTool

**Comment by Wegi** [comment]
Thanks for the feedback. Sounds like a nice idea. Will add it in the future.

**Comment by OSwoboda** [comment]
Additionally:
How many bonbons do you have for that Pokémon 
How many Pokémon of that kind are ready to be evolved

**Comment by n2o** [comment]
Your additions appear in #41

**Comment by Wegi** [comment]
Added Points 1, 2 and 3 in 375f1aa .

Rest will be added in version 1.0 in combination with the automatic top team feature.
