### ISSUE TITLE
Use current location

### ISSUE THREAD

**Issue by OSwoboda** [Phaetec/pogo-cruncher#33]
Instead of specifying a location manually it would be better to detect the users current location.
Additionally it's harder to detect that the user is using third party tools, because if I use cruncher and start the app afterwards, I'm presumably in another location. I don't want to insert lan lon coordinates at each login.

**Comment by Wegi** [comment]
Another good idea, will add in future

**Comment by n2o** [comment]
I will use HTML5 locations for this feature and implement it in the the assigned milestone.

**Comment by Wegi** [comment]
I'll change the whole thing to not use any location at all since we don't need it.

**Comment by n2o** [comment]
Nice, so we can close this for now and focus on the gps-less pgoapi
