### ISSUE TITLE
Show Bonbons and calculate Available Evolutions

### ISSUE THREAD

**Issue by Wegi** [Phaetec/pogo-cruncher#41]
Bonus: Only delete pokemon not needed for evolution.

- [x] Show bonbons
- [x] Show dust

**Comment by n2o** [comment]
- [ ] Show bonbons
- [ ] Show dust
- [ ] Show available Evolutions

**Comment by Wegi** [comment]
[ ] transmit candies
[ ] transmit dust

**Comment by Wegi** [comment]
Added APi endpoint for playerdata (name, pokecoins, stardust) in f55c9b8

**Comment by Wegi** [comment]
Done
