### ISSUE TITLE
Rename Pokemon according a scheme / IVs

### ISSUE THREAD

**Issue by Wegi** [Phaetec/pogo-cruncher#42]

**Comment by jccwright** [comment]
Seconded

**Comment by greedseed** [comment]
A renaming function of any kind would already be great :D

**Comment by n2o** [comment]
Yes, it is staged for the next big release

**Comment by n2o** [comment]
Which schemes do you prefer?
* AT!DF!ST
* IV%
* <Name-of-Pokemon>IV%
* ...

**Comment by romulof** [comment]
I'm manually renaming them using this pattern (python):
`new_name = "%.0f%% %d/%d/%d" % (iv_perfection, iv_attack, iv_defense, iv_stamina)`

That would result, for example:
- `53% 7/10/2`
- `97% 14/15/15`

But `100% 15/15/15` is bigger than maximum name allowed, so in case of perfection, I only rename to `100%`.

**Comment by n2o** [comment]
Sounds good! Thanks for your input

**Comment by n2o** [comment]
@Wegi: you'll get a list of Pokemon, which should be renamed. like:
```
[{"id": some-unique-number,
  "name": new-nickname},
 {...}]
```

**Comment by Wegi** [comment]
Added a route for renaming in 47a11a7 -> `api/pokemon/rename`

It expects the pokemon id as `id` and the desired nickname inside the `nickname` variable in the json request.

Also it Would be nice to have a scheme which shows IV% and Attack Types. (First Two Chars would suffice, i think)

Example:

Pokemon: Abra, Attacks Tackle (normal) and zen headbutt (psychic), 82% IV

Renames to:

No/Ps/ 82 (without whitespace to make 100% possible due to 12 char limitation.)

**Comment by Wegi** [comment]
@n2o changed it to accept a list in 9630fec
