### ISSUE TITLE
Crunching doesn't work anymore

### ISSUE THREAD

**Issue by OSwoboda** [Phaetec/pogo-cruncher#47]
I've sent a bunch of Pokémon away and there were no error messages. It said everything went ok, but all my Pokémon are still there.

**Comment by Wegi** [comment]
I just tried it, it still works. Did you per chance leave the pokemon window open for some time? If so the token may be expired. Try loging in anew and check if crunching works.

**Comment by n2o** [comment]
Tried it with fresh built docker images and also with the dev environment. No problem there. Can you please provide more information about your setup and your installation steps? We are heavily working on a more user-friendly solution...

**Comment by OSwoboda** [comment]
Ok it worked now, maybe it was because I logged in with the app on my smartphone after I've logged in into progo-cruncher? Anyway, thx for quick response.

**Comment by n2o** [comment]
Hm, maybe you're right. We will keep an eye on it! Thanks!
