### ISSUE TITLE
Frontend Selection-Features

### ISSUE THREAD

**Issue by Wegi** [Phaetec/pogo-cruncher#5]
It would be cool if there were buttons / actions to do the following:

- [x] Select all under X IV Percentage
- [x] Select all under Y CP
- [x] Select all non-favorites

**Comment by OSwoboda** [comment]
Would be nice if the duplicate selection would be a bit more advanced:
E.g. I want to evolve pidgeys and want to send away an amount of them according to the number of bonbons I currently have. Then there could be a function to take into account how many pidgeys I have to send away if I send the pidgeottos away after evolving.

**Comment by Wegi** [comment]
Good idea, will keep that in mind.

**Comment by Wegi** [comment]
A Select all but favorites button is needed as well.
