### ISSUE TITLE
Check if still connected to Niantic Server

### ISSUE THREAD

**Issue by n2o** [Phaetec/pogo-cruncher#50]
Combine this with the message returned by #49

**Comment by Wegi** [comment]
I added the endpoint `/api/status/niantic`. If connection could be tested per ECHo to niantic it returns a `{'status': 'ok'}` else you get a.
```
{'status': 'error',
                    'message': 'The connection to the Pokemon Go Servers could not be established. Please Logout and back in.'}
```

@n2o you can find it in 121390a

**Comment by n2o** [comment]
Also added in 80e640bdce712dd41a1b07476ee54a73f46a479f
