### ISSUE TITLE
Wrong error message when location could not be found

### ISSUE THREAD

**Issue by n2o** [Phaetec/pogo-cruncher#6]
app.py returns `Login failed - unexpected server response!` when i use a "wrong" location, e.g. Remscheid...

**Comment by Wegi** [comment]
Can you elaborate, what you mean with wrong location? I can log in fine using "Remscheid" as location.

**Comment by Wegi** [comment]
@Wegi will add a more detailed handling of different server status response codes.

**Comment by Wegi** [comment]
Parse exceptions during login and send them to the frontend udner status error.
