### ISSUE TITLE
Get All pokemons returns an empty list

### ISSUE THREAD

**Issue by h2xtreme** [Phaetec/pogo-cruncher#62]
OS: Windows 10 PRo
Docker: 1.12 for hyperV
Dokcer container launched as indicated in README. I can login but get all pokemons returns an empty list

**Comment by UltraHR** [comment]
Also getting this with precompiled (non-docker) Python release. Logs in and get total stardust/coins fine, but all pokemon returns empty.

**Comment by n2o** [comment]
That's interesting, because the connection to our API is obviously working. Do you have any error messages on your Console output in your browser?

**Comment by Wegi** [comment]
Can someone with this error post the console output of the docker console as well as the webconsole? (Ricght click Page -> Inspect -> Console.)

**Comment by Wegi** [comment]
Possibly solved this bug in the newest version. Please update and try again.

**Comment by h2xtreme** [comment]
I still have the same error. On firebug this pops up: "NetworkError: 500 INTERNAL SERVER ERROR - http://localhost:5000/api/pokemon"

docker logs returns this:

"/usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2016-08-08 08:31:15,211 CRIT Supervisor running as root (no user in config file)
2016-08-08 08:31:15,211 WARN No file matches via include "/etc/supervisor.d/*.ini"
2016-08-08 08:31:15,221 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-08-08 08:31:15,221 INFO supervisord started with pid 1
2016-08-08 08:31:16,223 INFO spawned: 'frontend' with pid 9
2016-08-08 08:31:16,224 INFO spawned: 'backend' with pid 10
2016-08-08 08:31:17,702 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-08-08 08:31:17,702 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)"

**Comment by h2xtreme** [comment]
Firefox Inspect element log:

 [424.947s] [om.next] transacted '[(app/loading {:status true})], #uuid "59c62641-cb44-4d87-baca-bd034c208b36"cruncher.js:537:210
 [425.286s] [om.next] transacted '[(app/loading {:status false})], #uuid "97990e0f-1b97-403f-bc2e-5e48671ccae7"cruncher.js:537:210
 [425.295s] [om.next] transacted '[(update/error {:message nil})], #uuid "f4d6a415-1470-4e80-8996-3555c129722e"cruncher.js:537:210

**Comment by MunchnetNL** [comment]
windows 7 
Developer setup 

Same, it doesnt pull a list of my pokemon. 
Console states: 

  File "app.py", line 96, in get_pokemon
    candies[candy_data['family_id']] = candy_data['candy']
KeyError: 'candy'
127.0.0.1 - - [08/Aug/2016 10:38:44] "GET /api/pokemon HTTP/1.1" 500 -

**Comment by n2o** [comment]
@h2xtreme seems like you're a dev, tool. Have you python3 installed? There are no logs since I had to use a supervisor to start two servers for the cruncher (api + frontend serving).

You can start our API with these commands:
```bash
$ pip install -r requirements.txt
$ python3 app.py
```

Then start the docker container with the frontend, but only the frontend and no API (because we manually started it with the command above):
```bash
$ docker run -p 8888:8888 phaetec/pogo-cruncher
```

Then you have all logs of the python API on your console

**Comment by MunchnetNL** [comment]
Console output: 

 [557.314s] [om.next] transacted '[(app/loading {:status true})], #uuid "98befe36-0d35-4689-97bd-6806bbe1c3e8"
cruncher.js:832 GET http://localhost:5000/api/pokemon 500 (INTERNAL SERVER ERROR)h.send @ cruncher.js:832h.Pd @ cruncher.js:844Vv @ cruncher.js:839$w @ cruncher.js:881ix @ cruncher.js:883jx @ cruncher.js:883kx @ cruncher.js:883(anonymous function) @ cruncher.js:956r @ cruncher.js:26i @ cruncher.js:24u @ cruncher.js:24p @ cruncher.js:24f @ cruncher.js:24r @ cruncher.js:28processEventQueue @ cruncher.js:24r @ cruncher.js:26handleTopLevel @ cruncher.js:26a @ cruncher.js:26perform @ cruncher.js:28batchedUpdates @ cruncher.js:26a @ cruncher.js:27dispatchEvent @ cruncher.js:26
cruncher.js:537  [557.824s] [om.next] transacted '[(app/loading {:status false})], #uuid "f86641f3-5e6d-4e1c-a1d7-ea0f97c7c3f1"
cruncher.js:537  [557.827s] [om.next] transacted '[(update/error {:message nil})], #uuid "83602457-a98c-4740-a16b-3cdb7080a752"
cruncher.js:882 Seems like you're not catching 'em all any more... INTERNAL SERVER ERROR

**Comment by Wegi** [comment]
I think i got it now. Please update your docker setup with `docker pull phaetec/pogo-cruncher` or try the newest release version https://github.com/Phaetec/pogo-cruncher/releases/tag/0.2.6-hotfix

**Comment by MunchnetNL** [comment]
0.2.6-hotfix solved the issue for me.

**Comment by h2xtreme** [comment]
For me too. Now it lists pokemons. I don't know if it's intended but candy available is blank and evolutions available is always 0.

**Comment by n2o** [comment]
Nice. @Wegi is already working on this issue @h2xtreme

**Comment by MunchnetNL** [comment]
for me I do get candy and available evolves. 
even did two evolves just to see how this works. 
Looking great guys !!

**Comment by Wegi** [comment]
@h2xtreme Can you try the newest hotfix version? Or via docker docker pull phaetec/pogo-cruncher ? 

I found an unrelated bug with evolution display, but it shouldn't affect candies.

**Comment by h2xtreme** [comment]
@Wegi everything works now. Thanks

I think you can close this.

**Comment by prefect4me** [comment]
@Wegi I just pulled new versions on OS X 10.11.6:

docker pull phaetec/pogo-cruncher
docker run -d -p 8888:8888 -p 5000:5000 phaetec/pogo-cruncher

Getting no 'Mon when loading list, error in console:

[Error] Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR) (pokemon, line 0)
[Debug]  [323.520s] [om.next] transacted '[(app/loading {:status false})], #uuid "ff7113af-82a1-4b6e-b2d4-25548eb61a59" (cruncher.js, line 562)
[Debug]  [323.530s] [om.next] transacted '[(update/error {:message nil})], #uuid "a85a4ec9-9bb3-4de5-9432-c899378d3c2a" (cruncher.js, line 562)
[Log] Seems like you're not catching 'em all any more... INTERNAL SERVER ERROR (cruncher.js, line 907)

**Comment by Wegi** [comment]
That looks, like the backend is not running, can you start the docker container and then check localhost:5000 in your browser. Does it load?
