### ISSUE TITLE
IV % not working

### ISSUE THREAD

**Issue by Mich43** [Phaetec/pogo-cruncher#63]
It does work only with 100% pokemon

**Comment by Wegi** [comment]
Can you try againwith the newest version and tell us if the error persists? If yes, can you post the output of the console please?

**Comment by Mich43** [comment]
Still not working, do you need output of chrome console or the python one?

**Comment by Wegi** [comment]
Both would be nice if possible.

**Comment by Mich43** [comment]
http://puu.sh/qtLtW/15ee59cfe5.png
http://pastebin.com/aDM2jABd
here

**Comment by Wegi** [comment]
Thank you, indeed in your case either the backend sends the percentage as 0 already, or the frontend has a conversion error. I can't replicate it at the moment.

Which python version are you using?

**Comment by Mich43** [comment]
2.7.12

**Comment by Wegi** [comment]
Found the bug, if the rest works as intended, i'll write a quick wrapper to correctly handle python 2.
Then both Python 2 and 3 should work. :)

**Comment by Wegi** [comment]
Should be working with python 2 now as well https://github.com/Phaetec/pogo-cruncher/releases/tag/0.2.7

**Comment by Mich43** [comment]
Thank you
