### ISSUE TITLE
Backend address is hard coded as localhost

### ISSUE THREAD

**Issue by sebnow** [Phaetec/pogo-cruncher#64]
Having the address hard coded prohibits hosting on external servers. The front end could at least use `window.location.hostname`.

**Comment by n2o** [comment]
Good idea, I already thought about adding a field where you can specify the URL to the API.

**Comment by n2o** [comment]
Available in about 20 minutes via DockerHub or directly with the source code of this repository

**Comment by n2o** [comment]
Oh, there are already 2 jobs in the queue. Will take a while to build this via dockerhub. Need to change and optimize this :-/ See status here: https://hub.docker.com/r/phaetec/pogo-cruncher/builds/ Tag: latest
