### ISSUE TITLE
Cross origin

### ISSUE THREAD

**Issue by Mich43** [Phaetec/pogo-cruncher#66]
cruncher.js:832 XMLHttpRequest cannot load http://:5000/api/login. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.h.send @ cruncher.js:832
cruncher.js:537  [ 20.070s] [om.next] transacted '[(app/loading {:status false})], #uuid "19971481-1f67-41f4-9ec2-a9c771244ba8"

When trying to login

**Comment by n2o** [comment]
Okay, the frontend was not able to parse your URL... Give me a minute...

**Comment by n2o** [comment]
Hotfix is on his way. You can pull the latest changes or wait for the completion of the [Docker image build process](https://hub.docker.com/r/phaetec/pogo-cruncher/builds/).

**Comment by n2o** [comment]
Try the latest image or the precompiled packages:

https://github.com/Phaetec/pogo-cruncher/releases/tag/0.2.7-hotfix

**Comment by Mich43** [comment]
All working fine, thank you for help :)

**Comment by n2o** [comment]
You're welcome!
