### ISSUE TITLE
0.2.7 precompiled version does not work

### ISSUE THREAD

**Issue by hhu94** [Phaetec/pogo-cruncher#67]
I'm trying to login but nothing happens after entering my google email address, password, location and checking the Google circle.

**Comment by djv2** [comment]
same, i click login and nothing happens. help

**Comment by n2o** [comment]
I had an idea and fixed a minor error. This might fix the problem for you. Please test the new release:
https://github.com/Phaetec/pogo-cruncher/releases/tag/0.2.7-hotfix

If this does not help, please provide some console output from your browser (Right Click somewhere --> Inspect --> Console)

**Comment by djv2** [comment]
that worked, thanks!

**Comment by hhu94** [comment]
Mine still doesn't work, but I found out why. I thought I could change the port the app is running on by passing in a port argument to the Flask object initialization but port 5000 is hardcoded all over the place.

I would suggest some kind of config file / parameter that allows changing the used port.

**Comment by n2o** [comment]
Hm okay, could think about it. But normally this port should not be used. Using the config file in the frontend would still be a problem.

**Comment by n2o** [comment]
@hhu94 5000 is not as deeply integrated as you might think. If you are compiling it yourself, you can easily change the port in [frontend/src/cruncher/config.clj](https://github.com/Phaetec/pogo-cruncher/blob/master/frontend/src/cruncher/config.cljs#L10). That's the only place where you need to change the port for the frontend to point to a different one.

After this, you have to re-create the JS-files with `lein do clean, cljsbuild once min`.

**Comment by n2o** [comment]
You can also do this in the docker container if you like and don't want to install Clojure. But you have to expose a different port with docker.

```
$ docker start <frontend-container>
$ docker exec -it <frontend-container> bash
$ cd /frontend
$ vim /src/cruncher/config.clj
$ lein do clean, cljsbuild once min
```
