### ISSUE TITLE
[Feature request] Rename Pokémons

### ISSUE THREAD

**Issue by romulof** [Phaetec/pogo-cruncher#77]
### Setup
- [X] I am using the latest version of this tool
- [X] Installed using Docker
- [ ] Installed via precompiled zip-Archive
- [ ] Cloned and locally built

---

### Description
After crunching my Pokémons, I usually rename them to their IVs, so I can see this info while in-game. For example:
`"Pikachu"` -> `"10/5/15"`

Currently I have to take a screenshot of the page, go to the game and rename manually there. Having an option to rename them in the browser would help a lot. Automated renaming would be super.

**Comment by Wegi** [comment]
Hi, this is already planned in issue #42 . I'll close this one for now. ;)
