### ISSUE TITLE
Safe to use still?

### ISSUE THREAD

**Issue by SeeingBlue** [Phaetec/pogo-cruncher#89]
I noticed this hasn't been updated since the new API came out. I assume this means it's not safe to use since nothing should be hitting the old API now.

**Comment by Wegi** [comment]
Let me check it out. I was out of the PoGo universe for a few week due to work related travels. I give a shout back as soon as I investigated.

**Comment by Wegi** [comment]
I just dug around a little bit. So yeah, apparently the API is again *not* safe to use. Thank you for bringing this to my attention. I would advise to not use the tool, until there is a save API we can use.
