### ISSUE TITLE
Baby mon cause error

### ISSUE THREAD

**Issue by yroc78** [Phaetec/pogo-cruncher#93]
Hatched a baby pokemon and now cruncher doesn't load. 
santa hat pikachu don't cause error checked with other account.
gen 2 babies seem to be the issue
posted code hope it helps. 
sorry I couldn't remember the site you had me use to make a link last time

---

### Setup
- [x] I am using the latest version of this tool
- [x] Installed using Docker
- [ ] Installed via precompiled zip-Archive
- [ ] Cloned and locally built

* Chrome / Chromium / ...: CTRL + SHIFT + I, then switch to the tab *Console*

Important are the red lines, which indicate an error.

### Other Console Output

```
Started Cruncher Version 0.3.1
cruncher.js:605  [306.693s] [om.next] transacted '[(app/loading {:status true})], #uuid "27b17e88-15e5-4e64-8172-35bff75bcac5"
cruncher.js:605  [306.720s] [om.next] transacted '[(status/niantic {:status true})], #uuid "98f3c00f-9605-41b5-8993-7d9996910205"
cruncher.js:605  [306.732s] [om.next] transacted '[(status/niantic {:status true})], #uuid "4c61f1f5-859e-4857-b98f-ee94e3b645d6"
cruncher.js:605  [318.243s] [om.next] transacted '[(app/loading {:status false})], #uuid "a240b6c8-9814-4a73-b147-b911bb553d9b"
cruncher.js:605  [318.248s] [om.next] transacted '[(update/error {:message nil})], #uuid "b5912b38-6772-4925-a55d-44671c8dece0"
cruncher.js:605  [318.250s] [om.next] transacted '[(user/logged-in {:status true})], #uuid "7e6caced-609b-4a2e-bf78-d5ba74425afb"
cruncher.js:605  [318.253s] [om.next] transacted '[(app/loading {:status true})], #uuid "e5b24b40-b30a-4213-a2c4-6232b3186200"
cruncher.js:605  [318.262s] [om.next] transacted '[(app/loading {:status true})], #uuid "339f4783-00ba-4a48-b883-ecdd4d6d2620"
cruncher.js:605  [318.270s] [om.next] transacted '[(change/view {:view :default})], #uuid "c9208f7e-f94b-424c-9121-a23c90f27eda"
http://localhost:5000/api/pokemon Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
cruncher.js:605  [322.448s] [om.next] transacted '[(app/loading {:status false})], #uuid "15ac1f7e-a6a6-4eb3-a87a-5c96f73e924e"
cruncher.js:605  [322.452s] [om.next] transacted '[(update/error {:message nil})], #uuid "541908c1-539f-4e83-83a6-34e9c9a852f8"
cruncher.js:951 Seems like you're not catching 'em all any more... INTERNAL SERVER ERROR
cruncher.js:605  [325.306s] [om.next] transacted '[(app/loading {:status false})], #uuid "6728e0e5-8cf1-4bcf-9eab-d3265f48694e"
cruncher.js:605  [325.310s] [om.next] transacted '[(update/error {:message nil})], #uuid "7347c078-51f4-47cf-b23d-36fecbe5872c"
cruncher.js:605  [325.316s] [om.next] transacted '[(update/player {:player {:level 28, :name "Piercedcory", :pokecoins 120, :stardust 411037}})], #uuid "74b5776d-049e-4174-a5db-d5c8a1d2516a"
```

**Comment by n2o** [comment]
Yes, I saw this coming when Niantic announced the new Pokemon ;-) Maybe I'll add this in the evening. Should not be the problem to implement a fallback Pokemon, although it whould be nice to have all the data of these mons in the table...

**Comment by n2o** [comment]
Added a fallback in 22d93866c248f56ac45d6a39530dfd60fea4ba21. It would be nice if you can test this release in some minutes after the pipelines have finished and report if there are any further problems.

This is just a fallback solution. We did not add those new pokemon to the database. But it should be sufficient to keep using this tool if you like. I am not sure whether there is any need for this tool since the missing features, which where implemented with this project are now available in the official client.

**Comment by n2o** [comment]
You should see Version number 0.3.2 in your console after a fresh `docker pull`. Might take up to 30 minutes until the new image is available for you.

**Comment by yroc78** [comment]
I'll test when i can. i still like having IV % instead of going by the
wording of the appraising feature.
And the sorting by IV is helpful as well.

**Comment by yroc78** [comment]
yeah still not working. heres the code I got
Started Cruncher Version 0.3.1
cruncher.js:605  [  0.354s] [om.next] transacted '[(status/niantic {:status true})], #uuid "46e779a2-ca56-4a1b-a485-aa667fffed06"
cruncher.js:605  [ 23.717s] [om.next] transacted '[(app/loading {:status true})], #uuid "e316d26d-cc2e-4fbe-9bc0-422c02a84101"
cruncher.js:605  [ 35.643s] [om.next] transacted '[(app/loading {:status false})], #uuid "6d004ea9-1089-4172-9263-2e76c8595aed"
cruncher.js:605  [ 35.648s] [om.next] transacted '[(update/error {:message "Failed to login. If the Pokemon GO Servers are online, your credentials may be wrong."})], #uuid "cc93ef85-cd75-4597-8510-a331f07df818"
cruncher.js:605  [40632.499s] [om.next] transacted '[(app/loading {:status true})], #uuid "cc389683-826a-4eac-a5f6-6c80adeb38d5"
cruncher.js:605  [40643.095s] [om.next] transacted '[(app/loading {:status false})], #uuid "6510e8ee-335a-489e-af2a-2da0ea738e04"
cruncher.js:605  [40643.098s] [om.next] transacted '[(update/error {:message nil})], #uuid "4df0cc6d-8024-4e57-a489-5206cf7121ca"
cruncher.js:605  [40643.102s] [om.next] transacted '[(user/logged-in {:status true})], #uuid "a6dce26d-2a6d-472b-9ed6-8848b5a05f2a"
cruncher.js:605  [40643.106s] [om.next] transacted '[(app/loading {:status true})], #uuid "646b08ae-7e74-4cfd-93ea-28f4a931f61d"
cruncher.js:605  [40643.111s] [om.next] transacted '[(app/loading {:status true})], #uuid "7455b396-c52d-4b1f-b558-23e7e7c45427"
cruncher.js:605  [40643.116s] [om.next] transacted '[(change/view {:view :default})], #uuid "7c3a6cbb-c4a5-4d97-a0d9-e95e2340cf3e"
http://localhost:5000/api/pokemon Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
cruncher.js:605  [40647.217s] [om.next] transacted '[(app/loading {:status false})], #uuid "752c959a-7f34-410e-82e4-02f1296a0104"
cruncher.js:605  [40647.221s] [om.next] transacted '[(update/error {:message nil})], #uuid "9c71224a-f18b-4210-936a-500bb14fe3bb"
cruncher.js:951 Seems like you're not catching 'em all any more... INTERNAL SERVER ERROR
cruncher.js:605  [40650.006s] [om.next] transacted '[(app/loading {:status false})], #uuid "d2f882ca-7f9a-4406-87d5-df876b7a5cc3"
cruncher.js:605  [40650.008s] [om.next] transacted '[(update/error {:message nil})], #uuid "0a81bbe6-fd4f-4960-8148-8701d97c06ef"
cruncher.js:605  [40650.012s] [om.next] transacted '[(update/player {:player {:level 36, :name

**Comment by n2o** [comment]
You are using an old version of the cruncher, version 0.3.1. You should see on your console the version 0.3.2.

**Comment by Wegi** [comment]
Can somebody with Version 0.3.2 test if it works?

**Comment by yroc78** [comment]
apologies I thought it had updated. it's working again. thank you

**Comment by n2o** [comment]
That's why I added the current version to the console output ;-)

You're welcome. It's just a workaround since I have to think about the future of the cruncher since the main missing feature arrived in the mobile client.
