### ISSUE TITLE
stuck on loading.......

### ISSUE THREAD

**Issue by yroc78** [Phaetec/pogo-cruncher#94]
### Setup
- [X] I am using the latest version of this tool
- [ ] Installed using Docker
- [ ] Installed via precompiled zip-Archive
- [ ] Cloned and locally built

### Browser Console Output
Started Cruncher Version 0.3.2
cruncher.js:605  [  6.276s] [om.next] transacted '[(app/loading {:status true})], #uuid "eebec73c-b808-4763-9e3e-15d17e418e16"
### Description
is it just me?
can't login

**Comment by n2o** [comment]
Hey, I can't confirm this. Tested it with the latest version and I am able to login via Google 2FA with no problems.

**Comment by yroc78** [comment]
damn. I've tried updating using docker and it just seems to not connect. I'll keep trying.

**Comment by yroc78** [comment]
restarted docker and it's back. please close/delete issue. my bad
