### ISSUE TITLE
login? or just me?

### ISSUE THREAD

**Issue by yroc78** [Phaetec/pogo-cruncher#95]
---

### Setup
- [X] I am using the latest version of this tool
- [X] Installed using Docker
- [ ] Installed via precompiled zip-Archive
- [ ] Cloned and locally built

### Browser Console Output
Each browser has a Dev-Console. Please open it and paste the output inside the
triple ticks (```). To open it, follow these steps:
* Chrome / Chromium / ...: CTRL + SHIFT + I, then switch to the tab *Console*
* Firefox: CTRL + SHIFT + I, then switch to the tab *Console"

Important are the red lines, which indicate an error.

```
Started Cruncher Version 0.3.2
cruncher.js:605  [  9.581s] [om.next] transacted '[(status/niantic {:status true})], #uuid "dbdb29b0-c87e-4a3e-bcad-5f346b2bdd92"
cruncher.js:605  [ 17.749s] [om.next] transacted '[(app/loading {:status true})], #uuid "d0cc1f2c-961b-4c88-bd59-828849c572e0"
cruncher.js:605  [ 20.295s] [om.next] transacted '[(app/loading {:status false})], #uuid "907851b5-6a1c-44f1-8ee7-23050045e223"
cruncher.js:605  [ 20.309s] [om.next] transacted '[(update/error {:message "Failed to login. If the Pokemon GO Servers are online, your credentials may be wrong."})], #uuid "8ba0d9bd-2c83-4acd-8cb2-d65696f3219e"
cruncher.js:605  [ 45.517s] [om.next] transacted '[(app/loading {:status true})], #uuid "8cb555cf-0820-464e-b6d8-b90ce52ae9ba"
cruncher.js:605  [ 47.827s] [om.next] transacted '[(app/loading {:status false})], #uuid "afcd4c1d-d16e-4c7b-a48c-22f036ac754d"
cruncher.js:605  [ 47.829s] [om.next] transacted '[(update/error {:message "Failed to login. If the Pokemon GO Servers are online, your credentials may be wrong."})], #uuid "0376c00b-7510-4934-b5cd-b4f7a9e0b0fa"
```

### Other Console Output
Are there any other errors? Paste them here:

```
# more output, which could be useful
```

---

### Description
Describe your problem here. (and delete this line)

**Comment by n2o** [comment]
Having the same error... Seems like they changed something.

**Comment by yroc78** [comment]
Damn it worked the other day. I was gonna trim my dex for the new 80 about to drop

**Comment by b-ffs** [comment]
Im experiencing the same issue. Any ideas on why ?

**Comment by yroc78** [comment]
@b-ffs guessing the update dropped new code like what happened with ditto. But 80x as much. Sad to lose such an awesome tool but the mods were getting frustrated with it.

**Comment by freefri** [comment]
Is this tool off maintenance? Is there any alternative for mass IV calculator?

**Comment by Wegi** [comment]
Yeah, it seems something changed in the API. I currently do not have the time to maintain the tool. I am not sure about @n2o, but its probably similar. If somebody is aware what was changed and wants to submit a pull request, we'll be more than happy to merge.

**Comment by yroc78** [comment]
@Wegi understandable. Wosh I understood this stuff more. This was a fantastic tool. Hopefully it can make a comeback. But it seems a lot of people are giving up on trying to keep up with all the changes

**Comment by n2o** [comment]
I'll give it a try and try to fix the Auth module if possible.

**Comment by n2o** [comment]
Okay, @Wegi and me have an idea how to fix this. We monkey-patched in the last release a script from pogoapidev to use location-less authentication. We will apply our changes to the latest pogoapi version to achieve the same results.

**Comment by n2o** [comment]
Hm, I am working on a workaroud to not use GPS location when logging in. The pgoapi devs dropped this feature last year and the current version does not support location-less login...

**Comment by yroc78** [comment]
that explains why a lot of pages died

**Comment by freefri** [comment]
I've run `docker pull phaetec/pogo-cruncher:develop` and `docker run -d -p 8888:8888 -p 5000:5000 phaetec/pogo-cruncher` and when I try to log with _Pokemon Trainer Club_ credentials in I'm still getting the error:

> Failed to login. If the Pokemon GO Servers are online, your credentials may be wrong.

Thank for your effort

**Comment by n2o** [comment]
I think you created a wrong container
`docker run -d -p 8888:8888 -p 5000:5000 phaetec/pogo-cruncher:develop`

I'll test it in an hour and give you feedback

**Comment by freefri** [comment]
I've tried with your command, and the same problem. But I'm having issues to log in with the official app as well, so maybe it is my problem. I'll check it again tomorrow.

**Comment by yroc78** [comment]
tried the code. same error :-( sucks they keep makin this game so complicated. I really loved the mass transfer with IV's all in one place with your program.

**Comment by n2o** [comment]
I tried it yesterday in the train, but got another error... Not that easy to get the old functionality back...

**Comment by yroc78** [comment]
I don't doubt it. I commend you guys for your great work.  Like i said ditto was a pain, so this had gotta be 80x worse

**Comment by fsfikke** [comment]
Is signing in with location again an option?

**Comment by n2o** [comment]
I tried to provide a non-valid option to provoke something like position-not-defined, but this produces error messages. Maybe we need to provide again positions...

**Comment by n2o** [comment]
Someone is experiencing the same issue as we are... One day it worked with the current pgoapi (that was the night when I pushed the new develop image) and the next day I am getting the same error 100... https://www.reddit.com/r/pokemongodev/comments/5w3x36/question_api_returns_status_code_100_session/

**Comment by n2o** [comment]
I created an issue at the pogodevs, maybe they have an idea (see https://github.com/pogodevorg/pgoapi/issues/188)

**Comment by n2o** [comment]
There is a pull request in the official repository fixing our issue. I applied these changes and a new dev image is currently building on dockerhub. Testing in when I am home. Worked on my laptop with Google 2FA

**Comment by fsfikke** [comment]
Sounds promising! Did you also test PTC or just Google? I can't login yet using PTC on the current version nor the develop branch.

**Comment by n2o** [comment]
Working on a new image, since google protobuf uses a library which is not available for Alpine Linux. This prevents users to login with the current develop image... Lokal execution of the code gives the desired result, but the Docker Image with Alpine produces a problem. And Docker Hub is currently having issues, which slowed the development process :-) I will test a PTC Account when the image is ready.

**Comment by n2o** [comment]
Okay, I am able to login with the latest image (Google + PTC), but I am not sure if everything is correct, since I accidently crunched all my pokemon from the testing account :D

**Comment by n2o** [comment]
Fixed in 5cf1f79045736cdfa5ad579dc72e964a756b69d1 and latest release v0.3.3

**Comment by n2o** [comment]
Should be fixed in the current release. Since Docker Hub is still having issues, you have to stay tuned when it is online.

Or you clone the repository and build the image on your machine:

```
docker build -t pogo .
docker run --rm -p 8888:8888 -p 5000:5000 pogo
```

Please be sure that you are using the latest version, check your JS console

**Comment by yroc78** [comment]
how do I build the image on my machine?

**Comment by rbialon** [comment]
@yroc78 Change to the directory containing the `Dockerfile` and run the `build` command from n2o's previous post.

**Comment by n2o** [comment]
It is on Docker Hub. Just pull the latest image as usual
`docker pull phaetec/pogo-cruncher`

**Comment by yroc78** [comment]
since I tried
```
cruncher.js:1389 Started Cruncher Version 0.3.3
cruncher.js:606  [  0.253s] [om.next] transacted '[(status/niantic {:status true})], #uuid "5db97598-6cf0-481b-b51a-d2103a19e3e5"
cruncher.js:606  [ 78.426s] [om.next] transacted '[(app/loading {:status true})], #uuid "b0891631-18e6-4ab1-a13b-eb87b745ad33"
cruncher.js:606  [ 84.848s] [om.next] transacted '[(app/loading {:status false})], #uuid "103e4dcf-b8d4-4ed7-b510-e635e695f889"
cruncher.js:606  [ 84.851s] [om.next] transacted '[(update/error {:message nil})], #uuid "b7442ccd-4108-4c83-8552-51b123e0943b"
cruncher.js:606  [ 84.857s] [om.next] transacted '[(user/logged-in {:status true})], #uuid "6ba176f1-a88c-4e68-a30f-d59abc7da8d9"
cruncher.js:606  [ 84.864s] [om.next] transacted '[(app/loading {:status true})], #uuid "4e06d392-a4b8-44c7-b134-d682c8a1fd1e"
cruncher.js:606  [ 84.883s] [om.next] transacted '[(app/loading {:status true})], #uuid "4dd7a7e4-47c4-4f47-afba-136577a25b1a"
cruncher.js:606  [ 84.898s] [om.next] transacted '[(change/view {:view :default})], #uuid "b4829fd4-6b7e-4505-bb2e-f767c15425d3"
cruncher.js:606  [ 85.995s] [om.next] transacted '[(app/loading {:status false})], #uuid "21c01070-bc11-49f1-ade0-cda20ea2418e"
cruncher.js:606  [ 86.000s] [om.next] transacted '[(update/error {:message "Login successful, but your inventory could not be loaded..."})], #uuid "0a14fc2e-dec7-4fd2-890a-6d95ca21cfa9"
cruncher.js:606  [ 86.092s] [om.next] transacted '[(app/loading {:status false})], #uuid "d2ed5b23-9ca7-496a-baf9-f53db9fd38a0"
cruncher.js:606  [ 86.095s] [om.next] transacted '[(update/error {:message "There was an error retrieving player data. If the error persists, try to log in anew."})], #uuid "68447fd1-57d8-44a3-b18e-9ae2a31c45a0"
cruncher.js:606  [108.239s] [om.next] transacted '[(app/loading {:status true})], #uuid "265c4687-c3c3-4320-9e44-0207b5b9b5ee"
cruncher.js:606  [109.354s] [om.next] transacted '[(app/loading {:status false})], #uuid "20450ebe-c55a-4c50-a3bf-bdc9cfaaaea8"
cruncher.js:606  [109.358s] [om.next] transacted '[(update/error {:message "Login successful, but your inventory could not be loaded..."})], #uuid "4eb053ad-bcc4-4b84-b4c8-8f391b35e1a8"```

**Comment by n2o** [comment]
Old version. Pull the latest version und CTRL SHIFT R your Browser. It is now version 0.4

**Comment by yroc78** [comment]
that work on mac? I thought I had done it

**Comment by n2o** [comment]
This works on all x64 / x86 OSs supporting Docker.

**Comment by yroc78** [comment]
still getting it
```cruncher.js:1439 Started Cruncher Version 0.4
cruncher.js:606  [  0.377s] [om.next] transacted '[(status/niantic {:status true})], #uuid "de02d59b-a097-4163-84e4-8a8f019e52eb"
cruncher.js:606  [ 30.504s] [om.next] transacted '[(app/loading {:status true})], #uuid "346d3103-93fb-44f6-876f-2c61d2cb19fa"
cruncher.js:606  [ 36.263s] [om.next] transacted '[(app/loading {:status false})], #uuid "03cd931f-d7d7-432a-9929-6f244773d69c"
cruncher.js:606  [ 36.266s] [om.next] transacted '[(update/error {:message nil})], #uuid "fccb8723-4b6d-45ee-b475-7006edd8d0cd"
cruncher.js:606  [ 36.272s] [om.next] transacted '[(user/logged-in {:status true})], #uuid "f972b3c3-a112-4419-8170-723969079eb3"
cruncher.js:606  [ 36.277s] [om.next] transacted '[(app/loading {:status true})], #uuid "eb7c81b9-d7df-41c3-8bfe-139568e6c2c3"
cruncher.js:606  [ 36.283s] [om.next] transacted '[(app/loading {:status true})], #uuid "445016d9-ea20-43aa-a488-a3a7d458d8d1"
cruncher.js:606  [ 36.289s] [om.next] transacted '[(change/view {:view :default})], #uuid "477d8ad9-894b-45e1-8c20-43d62fce3002"
cruncher.js:606  [ 37.535s] [om.next] transacted '[(app/loading {:status false})], #uuid "48f96f2c-6d4a-400d-8eb5-1736d87641d5"
cruncher.js:606  [ 37.539s] [om.next] transacted '[(update/error {:message "Login successful, but your inventory could not be loaded..."})], #uuid "667112a5-237d-40a0-8564-eb4d9ec013b7"
cruncher.js:606  [ 37.605s] [om.next] transacted '[(app/loading {:status false})], #uuid "95bfbee4-f706-46c1-96f8-9c1d4bf360de"
cruncher.js:606  [ 37.609s] [om.next] transacted '[(update/error {:message "There was an error retrieving player data. If the error persists, try to log in anew."})], #uuid "e2d8af11-1ec0-4294-bc6c-b3e9d08756bd"
```

**Comment by n2o** [comment]
How do you login? Google 2FA / PTC? I have no issues here with both...

**Comment by yroc78** [comment]
Google chrom local host 8888
With my gmail.
Using docker and pull requests from terminal.
Not sure ive set it up properly. 
Just did the steps in the wiki.
I'm new to all of this

**Comment by n2o** [comment]
But not with Two-factor-authentication (2FA), yes? So I need another account to verify the steps without 2FA and you should concern to use 2FA for security reasons ;-)

Just as an example: Imagine we phished your password with this application (we **don't**, you can verify this in the code), but if you do not use 2FA, you'd given us your "master"-password for your account. A malicious person could then have access to your account. But if you use 2FA, you'd just given us an app-password for this only purpose, just for one application, but not for the whole account.

**Comment by yroc78** [comment]
I'll have to look up how to set that up. Wasn't an issue till now.
Also the auto fill doesnt work with a new setup. 
Is that by that design?

**Comment by n2o** [comment]
This might come from the new form field... I do not use this feature in the cruncher.

**Comment by yroc78** [comment]
@n2o I have the 2 factor on now and now it doesn't let me in at all. and no alerts to my phone either

**Comment by yroc78** [comment]
2 factor auth app password enabled getting this
```
Started Cruncher Version 0.4
cruncher.js:606  [ 49.474s] [om.next] transacted '[(app/loading {:status true})], #uuid "e8668a4a-2b77-4812-a5ef-d1756e08bc2c"
cruncher.js:606  [ 49.516s] [om.next] transacted '[(status/niantic {:status true})], #uuid "69992bdb-308c-4e01-9d01-822470ae504f"
cruncher.js:606  [ 55.077s] [om.next] transacted '[(app/loading {:status false})], #uuid "c15be880-f903-4f8c-9655-f242c05f32d9"
cruncher.js:606  [ 55.081s] [om.next] transacted '[(update/error {:message nil})], #uuid "1d26b273-4d65-4851-b4b1-a77a2cf748da"
cruncher.js:606  [ 55.086s] [om.next] transacted '[(user/logged-in {:status true})], #uuid "5ca00677-a78b-4bb3-b43e-c64512915200"
cruncher.js:606  [ 55.092s] [om.next] transacted '[(app/loading {:status true})], #uuid "c139905f-488e-4b3d-b592-27a35153a0e6"
cruncher.js:606  [ 55.097s] [om.next] transacted '[(app/loading {:status true})], #uuid "5598012d-ae22-48b1-8716-36ff90bbe295"
cruncher.js:606  [ 55.105s] [om.next] transacted '[(change/view {:view :default})], #uuid "9ff36b8f-9b6b-48dc-8367-978d6b8aab95"
cruncher.js:606  [ 55.114s] [om.next] transacted '[(status/niantic {:status true})], #uuid "88d04f26-c39d-4af0-92b3-386601ccf4e4"
cruncher.js:606  [ 56.175s] [om.next] transacted '[(app/loading {:status false})], #uuid "e95fb65e-eadd-44ea-aae6-2e0d63874cd1"
cruncher.js:606  [ 56.177s] [om.next] transacted '[(update/error {:message "Login successful, but your inventory could not be loaded..."})], #uuid "18dc2807-8903-4e48-9dce-a8a94f85d19a"
cruncher.js:606  [ 56.247s] [om.next] transacted '[(app/loading {:status false})], #uuid "efd4e702-eb10-4c44-b9f0-d3aaef1c0549"
cruncher.js:606  [ 56.251s] [om.next] transacted '[(update/error {:message "There was an error retrieving player data. If the error persists, try to log in anew."})], #uuid "aadc62b1-240c-43ff-a11f-ffa3a98ee956"
cruncher.js:606  [ 65.947s] [om.next] transacted '[(app/loading {:status true})], #uuid "11d50638-458e-4946-b80b-bb5af8090c73"
cruncher.js:606  [ 67.033s] [om.next] transacted '[(app/loading {:status false})], #uuid "e24a03fe-2996-41d9-bf54-ddc6b1aa5e60"
cruncher.js:606  [ 67.037s] [om.next] transacted '[(update/error {:message "Login successful, but your inventory could not be loaded..."})], #uuid "c93b5a3e-4cd1-48f7-9e46-5b7b2b7ca494"
```

**Comment by yroc78** [comment]
how do you use it? @n2o

**Comment by n2o** [comment]
Now I'm getting the same error as you :D So annoying... I'll take a look at it after work.

**Comment by n2o** [comment]
Maybe related to https://github.com/pogodevorg/pgoapi/issues/189
The pogodevs have a smiliar issue and need to fix it somehow, because we are relying on their API... I'll take a look at it later

**Comment by yroc78** [comment]
Lol sorry to be the news breaker

**Comment by freefri** [comment]
I [quote](https://github.com/Phaetec/pogo-cruncher/issues/96) @n2o 

> GitHub Issues are not designed as a Chat replacement. We can use our [Discord](https://discordapp.com/channels/210684651549884416/210684698702249994) channel (see the badge in the README) for further discussions

So I think we have fixed another issue when this issue was closed, or the new discussion is a new issue. But the login seems to work for me using the Docker Hub image
